name: Hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "15 0 * * *"

permissions: {}

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
